# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b1981ac3847b1d9bb5cb8170998e7a84bb92237709bc8b1e32f6a8576fb9c3707950e16637359afbadf06b3859f1e423f01f34e7d2878ac7ef9e16f4fa26b5

test:
  secret_key_base: a7ce58295abb5974158371dabe1f94807df1973ce049ee91a73abe45c077c82e28166596baa7e080449ea53b9db6d6281fc8ff4a77b33bd74beaa5d8c6c5611b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
